### ISSUE TITLE
使用了redis ,那历史数据回滚怎么做，数据如何持久化

### ISSUE THREAD

**Issue by SSDespair** [Ahoo-Wang/govern-service#1]

**Comment by Ahoo-Wang** [comment]
1. 数据持久化能力是由redis提供的。
2. 历时数据回滚怎么做？没明白你的问题是什么？是指 配置回滚吗？

**Comment by SSDespair** [comment]
对的，配置回滚，怎么处理呢

**Comment by Ahoo-Wang** [comment]
配置回滚由 govern-service 框架处理，govern-service 维护了 配置的历史版本。

**Comment by Ahoo-Wang** [comment]
无回复时间过长，关闭此issue。
